### PR TITLE
bbc breaking news: weather exists and can hurt you

### PR DESCRIPTION
**Pull request by ameliarwig**
but i need to make weather spawn properly

### CODE REVIEW

**Comment by ameliarwig** [comment]
by that i mean, weather currently is only one storm that bounces around, would be cool to have random spawn and despawn for multiple weathers

**Comment by ameliarwig** [comment]
also i need graphics
like a whirlpool?

**Comment by dom-hall** [comment]
To be fair, it should be Amelia who is mad since she is the one writing the changes to existing code doc 😅 I'm just trying to make the job easier...

**Comment by ameliarwig** [comment]
> Need to add the Issues of changes or Dom will be mad

what is issues of changes

**Comment by dom-hall** [comment]
Creating a 'Change to Existing' GitHub Issue and linking it to this PR if you change any of the code we received from the other team - just saying what you changed and why.

**Review by printincident — APPROVED** [review]

**Pull request merged**
